// src/components/EmployeesTable/skillIconMap.ts
import {
    Code2,
    Atom,
    Server,
    Coffee,
    Database,
    BarChart2,
    TrendingUp,
    Users,
    UserCheck,
    Cloud,
    Briefcase,
    Handshake,
    DollarSign,
    FileText,
    BookOpen,
    Palette,
    Layers,
    Mail,
    Linkedin,
    Search,
    Settings,
    User,
    Award,
    ClipboardList,
    Presentation,
    ShieldCheck,
    Plug2,
    Facebook,
    FileSpreadsheet,
    Crown,
    MapPin,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

export const skillIconMap: Record<string, LucideIcon> = {
    "JavaScript": Code2,
    "React": Atom,
    "Node.js": Server,
    "Python": Code2,
    "Java": Coffee,
    "Spring Boot": Layers,
    "MySQL": Database,
    "Digital Marketing": BarChart2,
    "SEO": TrendingUp,
    "Analytics": BarChart2,
    "Strategy": ClipboardList,
    "Leadership": Award,
    "Brand Management": Users,
    "Team Leadership": Users,
    "Architecture": Layers,
    "Technical Strategy": Settings,
    "Cloud Architecture": Cloud,
    "CRM": Briefcase,
    "Negotiation": Handshake,
    "Customer Relations": UserCheck,
    "Sales Strategy": DollarSign,
    "Team Management": Users,
    "B2B Sales": Briefcase,
    "Strategic Sales": TrendingUp,
    "Market Analysis": Search,
    "Recruitment": User,
    "Employee Relations": Handshake,
    "HRIS": Settings,
    "HR Strategy": ClipboardList,
    "Policy Development": FileText,
    "Financial Modeling": FileSpreadsheet,
    "Excel": FileSpreadsheet,
    "SAP": FileSpreadsheet,
    "Financial Planning": ClipboardList,
    "Budget Management": DollarSign,
    "Accounting": BookOpen,
    "Tax Preparation": FileText,
    "QuickBooks": BookOpen,
    "Content Writing": FileText,
    "Social Media": Users,
    "Adobe Creative": Palette,
    "AWS": Cloud,
    "Docker": Server,
    "Kubernetes": Server,
    "Account Management": UserCheck,
    "Salesforce": Briefcase,
    "Presentation": Presentation,
    "Talent Acquisition": Search,
    "LinkedIn Recruiter": Linkedin,
    "Interviewing": UserCheck,
    "Test Automation": Settings,
    "Selenium": ShieldCheck,
    "API Testing": Plug2,
    "Google Ads": BarChart2,
    "Facebook Ads": Facebook,
    "Email Marketing": Mail,
};

export const positionIconMap: Record<string, React.ElementType> = {
    "CTO": Crown,
    "VP Marketing": Crown,
    "VP Sales": Crown,
    "Engineering Manager": UserCheck,
    "Marketing Manager": UserCheck,
    "Sales Manager": UserCheck,
    "HR Manager": UserCheck,
    "Finance Manager": UserCheck,
    "Senior Developer": Settings,
    "Junior Developer": User,
    "DevOps Engineer": Settings,
    "QA Engineer": Settings,
    "Sales Representative": Users,
    "Account Executive": Users,
    "Content Specialist": BarChart2,
    "Recruiter": UserCheck,
    "Financial Analyst": BarChart2,
    "HR Specialist": UserCheck,
    "Other": User,
};


export const positionColorMap: Record<string, string> = {
    "CTO": '#f59e42',
    "VP Marketing": '#e57373',
    "VP Sales": '#64b5f6',
    "Engineering Manager": '#81c784',
    "Marketing Manager": '#ba68c8',
    "Sales Manager": '#ffd54f',
    "HR Manager": '#4db6ac',
    "Finance Manager": '#9575cd',
    "Senior Developer": '#ff8a65',
    "Junior Developer": '#90caf9',
    "DevOps Engineer": '#a1887f',
    "QA Engineer": '#f06292',
    "Sales Representative": '#aed581',
    "Account Executive": '#7986cb',
    "Content Specialist": '#ffb74d',
    "Recruiter": '#4fc3f7',
    "Financial Analyst": '#dce775',
    "HR Specialist": '#ce93d8',
    "Other": '#b0bec5',
};


export const headerIconMap: Record<string, React.ElementType> = {
    Name: Users,
    Email: Mail,
    Department: Briefcase,
    Position: Layers,
    Location: MapPin,
    Skills: Award,
};
